### ISSUE TITLE
The lack of module

### ISSUE THREAD

**Issue by fxywky** [Mukosame/Zooming-Slow-Mo-CVPR-2020#10]
I can't find these in the .zip
from data import create_dataloader, create_dataset
from models import create_model

**Comment by Mukosame** [comment]
Hi, can you find this [__init__.py](https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/codes/data/__init__.py) in your path?

**Comment by fxywky** [comment]
yep，but create_model.py or def create_model() are not exist

**Comment by Mukosame** [comment]
Hi, you can find "creat_model()" [here](https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/codes/models/__init__.py).

**Comment by fxywky** [comment]
hahah，Thank U a lot，my fault
