### ISSUE TITLE
Generated video is two times longer

### ISSUE THREAD

**Issue by Vimos** [Mukosame/Zooming-Slow-Mo-CVPR-2020#12]
Is this because it inserted extra frames? Is there parameter to keep the length the same?

**Comment by htleeab** [comment]
https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/a0138d926a204d8865aca72339c1436ec90d996f/codes/video_to_zsm.py#L22
I guess you should set the higher output frame rate (e.g. twice of input frame rate)

**Comment by Vimos** [comment]
Thanks! I will try that!
