### ISSUE TITLE
Questions about generating LR images

### ISSUE THREAD

**Issue by littlewhitesea** [Mukosame/Zooming-Slow-Mo-CVPR-2020#17]
thanks for your excellent work. I met some problems in the stage of generating LR images.

1. I want to generate LR images via Python, so I run generate_mod_LR_bic.py, but I am told ''name 'imresize_np' is not defined''. I try to solve it, but don't  find 'imresize_np' in util.py of 'data' folder.

2. Are the input and output path in generate_mod_LR_bic.py identical to these of sep_vimeo_list.py? I set these path in the two python files same, the HR, LR and Bic folder can be created, but no images are produced in these folder.

Could you help me to solve above issues?

**Comment by Mukosame** [comment]
Hi, thanks for bringing this up! I forgot to put that function when creating this repo. I just made a new push to fix this issue.

The input of generate_mod_LR_bic.py is the HR path, the output path is where you want to put the generated LR images, and bicubic-upsampled images(usually we only use them as a baseline to compare with). 

The input of sep_vimeo_list.py is your input test/train/etc. images, it just cuts the files in the given list from the input path and pastes in your output path. It won't create any images, but just a cut/paste script to help you separate your test/train files from the whole Vimeo set, or separate the fast/medium/slow subsets from the test sets.

Hope these answers find you well :)

**Comment by littlewhitesea** [comment]
Thanks for your quick and detailed reply!

I added the function 'imresize_np' in the util.py, besides I also imported 'torch' and 'math' Library Functions, but I was told that 'calculate_weights_indices' function on the line 224 of util.py is unresolved reference.

Could you please help me again?

**Comment by Mukosame** [comment]
Hi, does the new update work?

**Comment by littlewhitesea** [comment]
No, it had some error when I run generate_mod_LR_bic.py. The response in the Python Console showed ''name 'calculate_weights_indices' is not defined'', which position is on the line 224 of util.py.

**Comment by Mukosame** [comment]
The function you jus mentioned is defined here: https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/codes/data/util.py#L212

**Comment by littlewhitesea** [comment]
Thank you very much, the update version can work.

**Comment by L4zyy** [comment]
You seem to forget to import torch and math to util.py at the new commit

**Comment by Mukosame** [comment]
@L4zyyThanks! You're right :)
