### ISSUE TITLE
Training stuck at epoch 0,iter 0

### ISSUE THREAD

**Issue by Marshall-yao** [Mukosame/Zooming-Slow-Mo-CVPR-2020#18]
Hi, 
 ### Problem: 
I follow the training instructions,but the training process stuck at epoch 0, iter 0. It can not continue to train.

### Specific implementations details: 
**1、compile the DCNv2.**
It raises a problem of  RuntimeError: Backward is not reentrant.  According to CharlesShang 's GitHub,  it may not be a serious problem  and  no one has give a solution.  So, i do not fix this problem.

**2、create_lmdb of train_GT and train_LR7**

- Split vimeo_setuplet into train and test set

- Downsample:  train set were downsamled to get train_LRx4 dataset.

- create train_GT and train_LR7 lmdb files:  

When creating lmdb files , it raise a issue of   "FileNotFoundError: [Errno 2] No such file or directory: '/home/dataset/vimeo7_train_GT.lmdb/meta_info.pkl'   "

So , I change the line 120 "Vimeo7_train_keys.pkl "  with " meta_info.pkl".  

**Generated train_GT and train_LR7 files are as follows:** 

/home/dataset/vimeo7_train_GT.lmdb/
data.mdb             153790088 kb
lock.mdb                     8kb
meta_info.pkl         1261kb

/home/dataset/vimeo7_train_LR7.lmdb/
data.mdb             10868344 kb
lock.mdb                   8kb
meta_info.pkl         1261kb

Does anyone have ideas ?

**Comment by Mukosame** [comment]
Hi Yao,

Your generated data looks correct to me. My training key is downloadable here: https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/datasets/meta_info/Vimeo7_train_keys.pkl, which should be identical with your meta_info.pkl.

Can you provide more details about how your code stuck? e.g. error info, appearance?

Thanks!

**Comment by Marshall-yao** [comment]
Thanks for your instant reply.

Code stuck is like this :

20-05-19 08:31:59.426 - INFO: Start training from epoch: 0, iter: 0

It can not continue to train and does not give any error information with 2  NVIDIA 2080Ti GPU.

I trained EDVR before . It takes about 2 minutes for 100 iterations.  This project is like EDVR.
But after 30 minutes and even longer time  , it is still at epoch 0, iter 0 and can not reach iter 100.  

I think may be the error of DCVv2 or  creating train and train_LR lmdb files.

Thanks.

**Comment by Marshall-yao** [comment]
Dear Mukosame,
I have found the  reason of train stuck. It is  the error of train lmdb file generation. 
I use the  Vimeo7_train_keys.pkl  file that you recommand  and it trains  normally.

**Comment by Mukosame** [comment]
Good to hear that. Please let me know if you have any other questions :)

**Comment by se16wangmeiwei** [comment]
> Dear Mukosame,
> I have found the reason of train stuck. It is the error of train lmdb file generation.
> I use the Vimeo7_train_keys.pkl file that you recommand and it trains normally.

Hi, I have met the same question with you. Could you tell how to generate the pkl file?

**Comment by Mukosame** [comment]
Hi @se16wangmeiwei , the pkl file is generated when creating the lmdb file. There is a small trick in [this script](https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/codes/data_scripts/create_lmdb_mp.py):

In this [line of code](https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/405c65b70e1df4268182d03f7bb539a3d9613e7b/codes/data_scripts/create_lmdb_mp.py#L120): it saves the meta info that we read previously to the pkl file in your given path.

**Comment by se16wangmeiwei** [comment]
Thank u for your reply! @Mukosame but I still have a question. after I ran the py file(create_lmdb_mp.py), I find that my Vimeo7_train_keys.pkl is different with yours. as following picture, my pkl file is a dict, but yours is just a list. I am very confused now. Looking forward your reply
![image](https://user-images.githubusercontent.com/31944875/115492721-ed002000-a294-11eb-9700-956fb48543e0.png)
