### ISSUE TITLE
error,help

### ISSUE THREAD

**Issue by shuyongzhang** [Mukosame/Zooming-Slow-Mo-CVPR-2020#2]
1. python test.py 

2.  报错误
    import utils.util as util
   ModuleNotFoundError: No module named 'utils.util'

这个utils.utils依赖什么库？
谢谢

**Comment by Mukosame** [comment]
Hi, thanks for your fast feedback! we haven't finished cleaning and upload all the code, including the utils.util. I'll let you know as soon as we finish this part.

另外，我们尽量用英文交流哈，这样能帮助更多人看懂~

**Comment by Mukosame** [comment]
Hi,
I've finished uploading all codes to this repo. Although some of them need to be updated, and the tutorial is still under construction, it should be able to run if you install all dependencies.

Now I'm working on writing the readme.md as well as fixing bugs in code. I'll keep you updated whenever there's a milestone commit :)

**Comment by Mukosame** [comment]
Hi,
The readme.md is updated. Hope you find it's helpful :)
