### ISSUE TITLE
Question about comparison to two-stage methods

### ISSUE THREAD

**Issue by hahahaprince** [Mukosame/Zooming-Slow-Mo-CVPR-2020#21]
Hi~ Thanks for your wonderful work! I have a question about comparison to two-stage methods. 
In your paper, the two-stage method is to first increase the frame rate and then super-resolution. Why not SR first and then VFI? Have you compared the difference between the two process?

**Comment by Mukosame** [comment]
Hi, this is a good question.
The main reason is to reduce computation. If we first perform SR before VFI, VFI will work on an HR space, which greatly increases the computation time. For the upscaling factor: 4, a VFI model running on HR frames will become around 16 times slower.

**Comment by hahahaprince** [comment]
Thanks for your reply~
