### ISSUE TITLE
error: identifier "THCState_getCurrentStream" is undefined

### ISSUE THREAD

**Issue by sourabh-patil** [Mukosame/Zooming-Slow-Mo-CVPR-2020#22]
Hi!
First of all thank you for sharing the code and you have done amazing work! I am following the instructions given by you. I am pasting the snippet of the error which is related to dcn_v2_cuda.cu file. I am trying to run it on my personal machine which does not have GPU. On my machine I can run make.sh from your repo and I can run it from CharlShangs repo too. Adding to that I can run its testcpu.py file on my personal machine. But as I will need GPU for further process so I am using my lab's GPU through vpn and ssh(due to current situation I am not in my campus). In that machine I am not able to run bash script. Following is the snippet of the error. Just for checking purpose I tried to run both your as well as CharlShangs bash script and error was the same. So I suppose there must be some issue with the remote server. Kindly let me know if you know about this issue. 

...DCNv2/src/cuda/dcn_v2_cuda.cu(107): error: identifier "THCState_getCurrentStream" is undefined

...DCNv2/src/cuda/dcn_v2_cuda.cu(279): error: identifier "THCState_getCurrentStream" is undefined

My personal system and remote server has torch 1.4.0 and torchvision 0.5.0. Remote server has same versions of torch and torchvision and cuda 10.2.

**Comment by sourabh-patil** [comment]
The issue was with the pytorch version I suppose, I installed pytorch 1.2.0 and I am able to run bash file. But I still get error of Jacobian mismatch which seems to be a known issue from CharlesShang repo.

**Comment by JensDA** [comment]
See [this DCNv2 pull request](https://github.com/CharlesShang/DCNv2/pull/58) for a fix.
