### ISSUE TITLE
Number of deformable groups used in Sakuya_arch.py

### ISSUE THREAD

**Issue by sourabh-patil** [Mukosame/Zooming-Slow-Mo-CVPR-2020#26]
In Sakuya_arch.py file, to execute deformable convolutions, authors are using numbers of groups as 8. So is it number of groups that we use in normal convolutions? If it is so then is there any reason to keep it as 8? Is it the same concept that was used in AlexNet paper to increase the computational efficiency or there is some other usage too?

**Comment by DAP-stay-well** [comment]
It is not for computational efficiency. The trick is firstly used in TDAN. With more groups of deformable Conv, the model will have a higher capacity to explore temporal contexts with sampling more different positions. It will improve temporal alignment performance.

**Comment by YapengTian** [comment]
It is not for computational efficiency. The trick is firstly used in TDAN. With more groups of deformable Conv, the model will have a higher capacity to explore temporal contexts with sampling more different positions. It will improve temporal alignment performance.

**Comment by sourabh-patil** [comment]
@YapengTian Thank you for the swift reply and thoughtful explanation!
