### ISSUE TITLE
ImportError: cannot import name 'DCN_sep'

### ISSUE THREAD

**Issue by ywu40** [Mukosame/Zooming-Slow-Mo-CVPR-2020#3]
Hello,

Thanks very much for sharing the code and your wonderful job. 
When run python test.py under Zooming-Slow-Mo-CVPR-2020/codes, got the following error. And I checked the the code under DCNv2 module, there is no DCN_sep class or function. Did you forget to check in some code?

Traceback (most recent call last):
  File "/root/Zooming-Slow-Mo-CVPR-2020/codes/models/modules/Sakuya_arch.py", line 9, in <module>
    from models.modules.DCNv2.dcn_v2 import DCN_sep
ImportError: cannot import name 'DCN_sep'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    import models.modules.Sakuya_arch as Sakuya_arch
  File "/root/Zooming-Slow-Mo-CVPR-2020/codes/models/modules/Sakuya_arch.py", line 11, in <module>
    raise ImportError('Failed to import DCNv2 module.')
ImportError: Failed to import DCNv2 module.

**Comment by Mukosame** [comment]
Did you follow the installation guide and compile the DCNv2?

**Comment by ywu40** [comment]
Thanks for your quick reply.
Yes, I followed the instruction of compile the DCNv2:
cd $ZOOMING_ROOT/codes/models/modules/DCNv2
bash make.sh         # build
python test.py    # run examples and gradient check

**Comment by Mukosame** [comment]
OK, the "python test.py " is DCNv2 folder is for testing if the compilation is successful. You can also attach the error info if you have any.

**Comment by Mukosame** [comment]
Hi, I figure out the error. I'll try to update the code to make it works :)
Thank you for bringing up this issue!

**Comment by Mukosame** [comment]
Hi, I just updated this repo. The problem should be solved now ^_^
You can either replace the dcnv2.py file if you have compiled successfully, or re-clone the whole directory.

**Comment by ywu40** [comment]
Thanks Mukosame.
I will fetch the code and merge the changes into the existing one.
