### ISSUE TITLE
why DAIN before EDVR

### ISSUE THREAD

**Issue by oliverxudd** [Mukosame/Zooming-Slow-Mo-CVPR-2020#35]
Hi Musosame, congrats on your achivement on this new task!

I have a question with regards to the order of the VFI and VSR method.
In your paper, DAIN with EDVR make a strong competitor for Zooming SlowMo. But why video frame interpolation before video super resolution? 
Intuitively, enhanced spatial resoltion will improve optical flow estimation, and then frame interpolation too. But not opposite. have you conduct experiment considering this factor? the order of VFI and VSR?

**Comment by Mukosame** [comment]
Hi @oliverxudd , this is really a good question.

The main reason is to reduce computation. If we first perform SR before VFI, VFI will work on an HR space, which greatly increases the computation time. For the upscaling factor: 4, a VFI model running on HR frames will become around 16 times slower, not to mention the high occupation of GPU memory.

**Comment by oliverxudd** [comment]
OK, that makes sense. thank you for your reply.
