### ISSUE TITLE
When the scene changes suddenly, the effect of inserting frames will not work

### ISSUE THREAD

**Issue by jiangzhiping** [Mukosame/Zooming-Slow-Mo-CVPR-2020#37]
When the scene changes suddenly, the effect of inserting frames will not work

**Comment by Mukosame** [comment]
Thanks for bringing this up. Currently we haven't handled the issue of scene changes and just assumed that the scene within one sequence remains the same. A quick hack is, you can first turn the target video into separate clips by comparing if the adjacent frames are of the same scene.
