### ISSUE TITLE
Is it possible to train a 2x model?

### ISSUE THREAD

**Issue by ycjing** [Mukosame/Zooming-Slow-Mo-CVPR-2020#38]
Hi @Mukosame 

Thank you for the great code! I wonder whether it is possible to train a 2x model. If it is, how to revise the model file? Thank you!

Best,
Yongcheng

**Comment by Mukosame** [comment]
hi @ycjing , yes it is possible, all you need to do is removing this line: https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/d97a5c00894202e117d26ebff3b3a8e534b35f97/codes/models/modules/Sakuya_arch.py#L342

**Comment by ycjing** [comment]
Hi @Mukosame 

Thank you for the warm help! I really appreciate it. I will try to train a 2x model with your suggested method.

Cheers,
Yongcheng
