### ISSUE TITLE
pip requirements missing

### ISSUE THREAD

**Issue by Wojak27** [Mukosame/Zooming-Slow-Mo-CVPR-2020#40]
Hi! I was wondering if it would be possible to provide pip requirements.txt file for the anaconda environment since all of the packages need to be compatible also with the DCNv2 package. I ran into some environment problems

**Comment by Mukosame** [comment]
No problem. Would you like to provide more detailed info about your current environment (os, cuda version, gcc version, pytorch version, etc.) and what errors you encountered?

**Comment by Mukosame** [comment]
Hi, the requirement.txt is updated https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/requirements.txt. Let me know if you have any more environment questions!
