### ISSUE TITLE
Change number of interpolations

### ISSUE THREAD

**Issue by roicort** [Mukosame/Zooming-Slow-Mo-CVPR-2020#42]
Is it possible to change the number of interpolated frames between the original frames? 

Amazing work, btw. :)

**Comment by Mukosame** [comment]
Hi, thanks for your interest!
In the current structure, we cannot change. But you can interpolate multiple times --- well the output size will also increase by 4^n.
We are working on a new version of this network. In the new one, we can change the number of interpolated frames in between.

**Comment by roicort** [comment]
Thank you for your kind reply!
That's a good idea in the meantime, could work.
Glad to hear you are working on something new :) 
Stay safe,

R.
