### ISSUE TITLE
Vimeo-septuplet directory structure

### ISSUE THREAD

**Issue by yzfly** [Mukosame/Zooming-Slow-Mo-CVPR-2020#43]
Hello, thank you for your wonderful work.  However, as a newbie, I am very confused about how to generate LR images and lmdb files. Can you share your Vimeo-septuplet directory structure? This will help better understand the data processing flow.

**Comment by Mukosame** [comment]
Hi @yzfly , thanks a lot for your nice suggestion! I just updated the readme file about this part. (https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/README.md#part-1-data-preparation)

Hope you find it helpful!

**Comment by yzfly** [comment]
That's good. Thank you!
