### ISSUE TITLE
URL in paper is written in correct

### ISSUE THREAD

**Issue by marwansalem** [Mukosame/Zooming-Slow-Mo-CVPR-2020#47]
The URL for this repo is written incorrectly in the paper
https://github.com/Mukosame/Zooming-SlowMo-CVPR-2020 ,
The correct one:
https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020 it is missing a hyphen.

Paper taken from CVPR website.
https://openaccess.thecvf.com/content_CVPR_2020/papers/Xiang_Zooming_Slow-Mo_Fast_and_Accurate_One-Stage_Space-Time_Video_Super-Resolution_CVPR_2020_paper.pdf

**Comment by Mukosame** [comment]
Thanks for finding this....it is really embarrassing that nobody discovers this in the past 1 year.
Since we cannot change the cvpr version now, we will open another repo with the url above and link it to this repo.
