### ISSUE TITLE
Testing is killed 

### ISSUE THREAD

**Issue by 13610JACK** [Mukosame/Zooming-Slow-Mo-CVPR-2020#49]
I has used the make.sh and test the test.py. Then I download the pretrained model, and use the model to do the Test by：python video_to_zsm.py --video ../input.mp4 --model ../experiments/pretrained_models/xiang2020zooming.pth --output ../huanhuan.mp4.
But there is one issue about the kill:
ffmpeg -i ../zoom_Huanhuan-Z_1436x806.mp4 -vsync 0 .delme/%06d.png
ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.2.0 (crosstool-NG fa8859cb)
  configuration: --prefix=/root/miniconda3/envs/myconda --cc=/opt/conda/conda-bld/ffmpeg_1531088893642/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --enable-shared --enable-static --enable-zlib --enable-pic --enable-gpl --enable-version3 --disable-nonfree --enable-hardcoded-tables --enable-avresample --enable-libfreetype --disable-openssl --disable-gnutls --enable-libvpx --enable-pthreads --enable-libopus --enable-postproc --disable-libx264
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../zoom_Huanhuan-Z_1436x806.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2020-11-27T10:10:34.000000Z
  Duration: 00:00:09.00, start: 0.000000, bitrate: 419 kb/s
    Chapter #0:0: start 0.000000, end 9.000000
    Metadata:
      title           : Sharing Started
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 126 kb/s (default)
    Metadata:
      creation_time   : 2020-11-27T10:10:34.000000Z
      handler_name    : AAC audio
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1436x806, 290 kb/s, 25 fps, 25 tbr, 30k tbn, 60k tbc (default)
    Metadata:
      creation_time   : 2020-11-27T10:10:34.000000Z
      handler_name    : H.264/AVC video
      encoder         : AVC Coding
    Stream #0:2(und): Data: bin_data (text / 0x74786574), 0 kb/s
    Metadata:
      creation_time   : 2020-11-27T10:10:34.000000Z
      handler_name    : Text
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '.delme/%06d.png':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf58.12.100
    Chapter #0:0: start 0.000000, end 9.000000
    Metadata:
      title           : Sharing Started
    Stream #0:0(und): Video: png, rgb24, 1436x806, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc (default)
    Metadata:
      creation_time   : 2020-11-27T10:10:34.000000Z
      handler_name    : H.264/AVC video
      encoder         : Lavc58.18.100 png
frame=  225 fps=112 q=-0.0 Lsize=N/A time=00:00:09.00 bitrate=N/A speed=4.48x    
video:64690kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Killed

**Comment by Mukosame** [comment]
Looks like the problem is on ffmpeg. We received some feedbacks about this issue, that the ffmpeg is not always compatible to everybody's environment. So I suggest you to extract the video in separate frames for now, and run run our script again, then combine the output frames back into a video clip.
