### ISSUE TITLE
Zooming-Slow-Mo-CVPR-2020/codes/models/modules/DCNv2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: 

### ISSUE THREAD

**Issue by hanlei1995** [Mukosame/Zooming-Slow-Mo-CVPR-2020#54]
After i run make.sh,i run the test.py. I got an error:Zooming-Slow-Mo-CVPR-2020/codes/models/modules/DCNv2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol:  _ZNK2at11ATenOpTable11reportErrorEN3c1012TensorTypeIdE. Could you help me?thank you.

**Comment by littlewhitesea** [comment]
I met a similar problem like you. After I changed the version of pytorch, I finally solved this question.

I used anaconda to install the pytorch. The version of python was 3.8. I firstly created a virtual environment using the following command: **conda create -n zooming python=3.8**

Then, in the virtual environment, I performed the command: **conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch**
