### ISSUE TITLE
question about create_lmdb_mp.py

### ISSUE THREAD

**Issue by candygogogogo** [Mukosame/Zooming-Slow-Mo-CVPR-2020#55]
when i run create_lmdb_mp.py . found the errno is :no such file or directory : 'meta_info.pkl '.
But I don't know what Meta_Info.pkl is. How to create it.
Your reply is very important to me. please!

**Comment by Coding-jpg** [comment]
did you get it now? i found the same error :( @candygogogogo

**Comment by Mukosame** [comment]
Hi, if you want to create the training dataset, you can replace the path with this: https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/datasets/meta_info/Vimeo7_train_keys.pkl
the meta_info.pkl stands for the key.pkl file for training/testing.
