### ISSUE TITLE
How can i train and test my datasets?

### ISSUE THREAD

**Issue by further-home** [Mukosame/Zooming-Slow-Mo-CVPR-2020#63]
When i want to train my datasets, i should  wirte .yml file? When i want to test my datasets, i must train?please tell me how to test .Thanks !

**Comment by Mukosame** [comment]
Hi, thanks for your interest in our work! Yes, you need to edit the .yml to be applicable to your dataset.
As for testing, you can either use your own trained model, or directly apply our pretrained weights. Please check https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020#testing for more details.

**Comment by further-home** [comment]
Hi,thank you for answering my questions!I want to ask whether size = n / A is abnormal during the test.&nbsp;My test data always reports an error when tested, as shown in the figure below&nbsp;.I want to as I want to ask if the. YML file format is written according to the file format provided by you.How much memory does the training data occupy and how long is it appropriate.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mukosame/Zooming-Slow-Mo-CVPR-2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 中午1:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mukosame/Zooming-Slow-Mo-CVPR-2020] How can i train and test my datasets? (#63)





 
Hi, thanks for your interest in our work! Yes, you need to edit the .yml to be applicable to your dataset.
 As for testing, you can either use your own trained model, or directly apply our pretrained weights. Please check https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020#testing for more details.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mukosame** [comment]
1. Size = N/A is abnormal. It means the data is not read properly;
2. Sorry that I cannot see the figure you pointed. Try to paste the error log or post a link of your image?
3. The yml file is just the config of the training. It should keep the same arguments, while you can change the specific settings according to your requirement;
4. It depends on you length of sequence, patch size and batch size. If you suspect OOM, you could reduce these numbers.

**Comment by further-home** [comment]
this is error log



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mukosame/Zooming-Slow-Mo-CVPR-2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mukosame/Zooming-Slow-Mo-CVPR-2020] How can i train and test my datasets? (#63)





  
Size = N/A is abnormal. It means the data is not read properly;
 
Sorry that I cannot see the figure you pointed. Try to paste the error log or post a link of your image?
 
The yml file is just the config of the training. It should keep the same arguments, while you can change the specific settings according to your requirement;
 
It depends on you length of sequence, patch size and batch size. If you suspect OOM, you could reduce these numbers.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by further-home** [comment]
Are you Chinese?can i have your wechat!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mukosame/Zooming-Slow-Mo-CVPR-2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mukosame/Zooming-Slow-Mo-CVPR-2020] How can i train and test my datasets? (#63)





  
Size = N/A is abnormal. It means the data is not read properly;
 
Sorry that I cannot see the figure you pointed. Try to paste the error log or post a link of your image?
 
The yml file is just the config of the training. It should keep the same arguments, while you can change the specific settings according to your requirement;
 
It depends on you length of sequence, patch size and batch size. If you suspect OOM, you could reduce these numbers.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by further-home** [comment]
Is this error caused by my data？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mukosame/Zooming-Slow-Mo-CVPR-2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mukosame/Zooming-Slow-Mo-CVPR-2020] How can i train and test my datasets? (#63)





  
Size = N/A is abnormal. It means the data is not read properly;
 
Sorry that I cannot see the figure you pointed. Try to paste the error log or post a link of your image?
 
The yml file is just the config of the training. It should keep the same arguments, while you can change the specific settings according to your requirement;
 
It depends on you length of sequence, patch size and batch size. If you suspect OOM, you could reduce these numbers.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by further-home** [comment]
Hi!
&nbsp;&nbsp; This is error log,can you help me to solve this problem?Thanks

&nbsp; Stream mapping:
&nbsp; Stream #0:0 -&gt; #0:0 (h264 (native) -&gt; png (native))
Press [q] to stop, [?] for help
frame=22078 fps= 64 q=-0.0 Lsize=N/A time=00:12:16.66 bitrate=N/A&nbsp;&nbsp; &nbsp;
video:81678277kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mukosame/Zooming-Slow-Mo-CVPR-2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mukosame/Zooming-Slow-Mo-CVPR-2020] How can i train and test my datasets? (#63)





  
Size = N/A is abnormal. It means the data is not read properly;
 
Sorry that I cannot see the figure you pointed. Try to paste the error log or post a link of your image?
 
The yml file is just the config of the training. It should keep the same arguments, while you can change the specific settings according to your requirement;
 
It depends on you length of sequence, patch size and batch size. If you suspect OOM, you could reduce these numbers.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
