### ISSUE TITLE
some questions about testing

### ISSUE THREAD

**Issue by Juniiyao** [Mukosame/Zooming-Slow-Mo-CVPR-2020#72]
Excuse me, when we test the two-stage model, should we insert frames for LR video sequence or HR video sequence in the first Stage(VFI) ?
I tried to insert frames for HR video sequence and then downsamp them to the second stage (VSR), and the results were all higher than those in the paper. 
thank you for your reply!

**Comment by Mukosame** [comment]
Hi @Juniiyao , in this paper, the inputs are half-length and downsampled ones. I conduct VFI first to generate the full sequence (GT-interpolated-GT-...), and then upsample using VSR.
Since in actual practice, we do not have HR video to start with, so the above procedure makes more sense.
